// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor_status.proto

/*
Package monitor_system is a generated protocol buffer package.

It is generated from these files:
	monitor_status.proto

It has these top-level messages:
	AgentServerStatusResponse
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// agent服务状态响应包
type AgentServerStatusResponse struct {
	StrLocalIp       *string `protobuf:"bytes,1,req,name=str_local_ip,json=strLocalIp" json:"str_local_ip,omitempty"`
	LocalPort        *uint32 `protobuf:"varint,2,req,name=local_port,json=localPort" json:"local_port,omitempty"`
	CollectInterval  *uint32 `protobuf:"varint,3,req,name=collect_interval,json=collectInterval" json:"collect_interval,omitempty"`
	ZkHosts          *string `protobuf:"bytes,4,req,name=zk_hosts,json=zkHosts" json:"zk_hosts,omitempty"`
	ZkAgentPath      *string `protobuf:"bytes,5,req,name=zk_agent_path,json=zkAgentPath" json:"zk_agent_path,omitempty"`
	ZkProxyPath      *string `protobuf:"bytes,6,req,name=zk_proxy_path,json=zkProxyPath" json:"zk_proxy_path,omitempty"`
	ZkCheckInterval  *uint32 `protobuf:"varint,7,req,name=zk_check_interval,json=zkCheckInterval" json:"zk_check_interval,omitempty"`
	QueueName        *string `protobuf:"bytes,8,req,name=queue_name,json=queueName" json:"queue_name,omitempty"`
	QueueEleSize     *uint32 `protobuf:"varint,9,req,name=queue_ele_size,json=queueEleSize" json:"queue_ele_size,omitempty"`
	QueueEleCount    *uint32 `protobuf:"varint,10,req,name=queue_ele_count,json=queueEleCount" json:"queue_ele_count,omitempty"`
	ProcessCount     *uint64 `protobuf:"varint,11,req,name=process_count,json=processCount" json:"process_count,omitempty"`
	ProcessPerSec    *uint64 `protobuf:"varint,12,req,name=process_per_sec,json=processPerSec" json:"process_per_sec,omitempty"`
	ProxySize        *uint32 `protobuf:"varint,13,req,name=proxy_size,json=proxySize" json:"proxy_size,omitempty"`
	AttrSize         *uint32 `protobuf:"varint,14,req,name=attr_size,json=attrSize" json:"attr_size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AgentServerStatusResponse) Reset()                    { *m = AgentServerStatusResponse{} }
func (m *AgentServerStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*AgentServerStatusResponse) ProtoMessage()               {}
func (*AgentServerStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AgentServerStatusResponse) GetStrLocalIp() string {
	if m != nil && m.StrLocalIp != nil {
		return *m.StrLocalIp
	}
	return ""
}

func (m *AgentServerStatusResponse) GetLocalPort() uint32 {
	if m != nil && m.LocalPort != nil {
		return *m.LocalPort
	}
	return 0
}

func (m *AgentServerStatusResponse) GetCollectInterval() uint32 {
	if m != nil && m.CollectInterval != nil {
		return *m.CollectInterval
	}
	return 0
}

func (m *AgentServerStatusResponse) GetZkHosts() string {
	if m != nil && m.ZkHosts != nil {
		return *m.ZkHosts
	}
	return ""
}

func (m *AgentServerStatusResponse) GetZkAgentPath() string {
	if m != nil && m.ZkAgentPath != nil {
		return *m.ZkAgentPath
	}
	return ""
}

func (m *AgentServerStatusResponse) GetZkProxyPath() string {
	if m != nil && m.ZkProxyPath != nil {
		return *m.ZkProxyPath
	}
	return ""
}

func (m *AgentServerStatusResponse) GetZkCheckInterval() uint32 {
	if m != nil && m.ZkCheckInterval != nil {
		return *m.ZkCheckInterval
	}
	return 0
}

func (m *AgentServerStatusResponse) GetQueueName() string {
	if m != nil && m.QueueName != nil {
		return *m.QueueName
	}
	return ""
}

func (m *AgentServerStatusResponse) GetQueueEleSize() uint32 {
	if m != nil && m.QueueEleSize != nil {
		return *m.QueueEleSize
	}
	return 0
}

func (m *AgentServerStatusResponse) GetQueueEleCount() uint32 {
	if m != nil && m.QueueEleCount != nil {
		return *m.QueueEleCount
	}
	return 0
}

func (m *AgentServerStatusResponse) GetProcessCount() uint64 {
	if m != nil && m.ProcessCount != nil {
		return *m.ProcessCount
	}
	return 0
}

func (m *AgentServerStatusResponse) GetProcessPerSec() uint64 {
	if m != nil && m.ProcessPerSec != nil {
		return *m.ProcessPerSec
	}
	return 0
}

func (m *AgentServerStatusResponse) GetProxySize() uint32 {
	if m != nil && m.ProxySize != nil {
		return *m.ProxySize
	}
	return 0
}

func (m *AgentServerStatusResponse) GetAttrSize() uint32 {
	if m != nil && m.AttrSize != nil {
		return *m.AttrSize
	}
	return 0
}

func init() {
	proto.RegisterType((*AgentServerStatusResponse)(nil), "monitor_system.AgentServerStatusResponse")
}

func init() { proto.RegisterFile("monitor_status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0xdf, 0x8a, 0xd4, 0x30,
	0x14, 0x87, 0x71, 0x1c, 0xdd, 0xe9, 0xd9, 0xe9, 0x8c, 0x06, 0x2f, 0xb2, 0xc8, 0xc2, 0xb0, 0xca,
	0x32, 0x7a, 0xe1, 0x3b, 0xc8, 0x22, 0xb8, 0x20, 0x52, 0xda, 0x07, 0x08, 0x21, 0x1c, 0x6c, 0xe9,
	0x9f, 0xc4, 0xe4, 0x74, 0x71, 0xf3, 0x0c, 0x3e, 0xf4, 0x92, 0x93, 0x76, 0xf7, 0xb2, 0xdf, 0xef,
	0x6b, 0xfa, 0xd1, 0xc0, 0x87, 0xd1, 0x4e, 0x1d, 0x59, 0xaf, 0x02, 0x69, 0x9a, 0xc3, 0x37, 0xe7,
	0x2d, 0x59, 0x71, 0x78, 0xa6, 0x8f, 0x81, 0x70, 0xbc, 0xf9, 0xbf, 0x85, 0xab, 0xef, 0x7f, 0x70,
	0xa2, 0x06, 0xfd, 0x03, 0xfa, 0x86, 0xdd, 0x1a, 0x83, 0xb3, 0x53, 0x40, 0x71, 0x82, 0x7d, 0x20,
	0xaf, 0x06, 0x6b, 0xf4, 0xa0, 0x3a, 0x27, 0x5f, 0x9d, 0x36, 0xe7, 0xa2, 0x86, 0x40, 0xfe, 0x57,
	0x42, 0xf7, 0x4e, 0x5c, 0x03, 0xe4, 0xd5, 0x59, 0x4f, 0x72, 0x73, 0xda, 0x9c, 0xcb, 0xba, 0x60,
	0x52, 0x59, 0x4f, 0xe2, 0x0b, 0xbc, 0x33, 0x76, 0x18, 0xd0, 0x90, 0xea, 0x26, 0x42, 0xff, 0xa0,
	0x07, 0xf9, 0x9a, 0xa5, 0xe3, 0xc2, 0xef, 0x17, 0x2c, 0xae, 0x60, 0x17, 0x7b, 0xd5, 0xda, 0x40,
	0x41, 0x6e, 0xf9, 0x3b, 0x17, 0xb1, 0xff, 0x99, 0x1e, 0xc5, 0x0d, 0x94, 0xb1, 0x57, 0x3a, 0x65,
	0x2a, 0xa7, 0xa9, 0x95, 0x6f, 0x78, 0xbf, 0x8c, 0x3d, 0xa7, 0x57, 0x9a, 0xda, 0xc5, 0x71, 0xde,
	0xfe, 0x7b, 0xcc, 0xce, 0xdb, 0xd5, 0xa9, 0x12, 0x63, 0xe7, 0x2b, 0xbc, 0x8f, 0xbd, 0x32, 0x2d,
	0x9a, 0xfe, 0x25, 0xe7, 0x22, 0xe7, 0xc4, 0xfe, 0x2e, 0xf1, 0xe7, 0x9c, 0x6b, 0x80, 0xbf, 0x33,
	0xce, 0xa8, 0x26, 0x3d, 0xa2, 0xdc, 0xf1, 0x61, 0x05, 0x93, 0xdf, 0x7a, 0x44, 0xf1, 0x19, 0x0e,
	0x79, 0xc6, 0x01, 0x55, 0xe8, 0x22, 0xca, 0x82, 0xcf, 0xd9, 0x33, 0xfd, 0x31, 0x60, 0xd3, 0x45,
	0x14, 0xb7, 0x70, 0x7c, 0xb1, 0x8c, 0x9d, 0x27, 0x92, 0xc0, 0x5a, 0xb9, 0x6a, 0x77, 0x09, 0x8a,
	0x4f, 0x50, 0x3a, 0x6f, 0x0d, 0x86, 0xb0, 0x58, 0x97, 0xa7, 0xcd, 0x79, 0x5b, 0xef, 0x17, 0x98,
	0xa5, 0x5b, 0x38, 0xae, 0x92, 0x43, 0xaf, 0x02, 0x1a, 0xb9, 0x67, 0x6d, 0x7d, 0xb7, 0x42, 0xdf,
	0xa0, 0x49, 0xe5, 0xf9, 0x37, 0x70, 0x56, 0x99, 0xaf, 0x84, 0x09, 0x37, 0x7d, 0x84, 0x42, 0x13,
	0xf9, 0xbc, 0x1e, 0x78, 0xdd, 0x25, 0x90, 0xc6, 0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x6c,
	0x35, 0xd6, 0x35, 0x02, 0x00, 0x00,
}
